/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AustinSite": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "Edge": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}